### ISSUE TITLE
How to use TCC to compile complex programs

### ISSUE THREAD

**Issue by Edward-Elric233** [vowstar/k210-linux-nommu#13]
I am a novice, and when I followed the README, I found that I could not compile using the following command
![image](https://user-images.githubusercontent.com/45136205/122152294-a6453580-ce93-11eb-94da-e2e8699508f2.png)
When I modify the program name and add the -nostdlib parameter, the program runs successfully
![image](https://user-images.githubusercontent.com/45136205/122152474-ec01fe00-ce93-11eb-8f50-f55c270d4472.png)
But when I wanted to make the program more complex, I found that I couldn't do it.It seemed like I should include a header file, but I didn't know how to do it, and I tried for a long time without success.Any help will be greatly appreciated
![image](https://user-images.githubusercontent.com/45136205/122154100-cf1afa00-ce96-11eb-96a7-d2a18fbd9c79.png)

**Comment by Edward-Elric233** [comment]
> I am a novice, and when I followed the README, I found that I could not compile using the following command
> ![image](https://user-images.githubusercontent.com/45136205/122152294-a6453580-ce93-11eb-94da-e2e8699508f2.png)
> When I modify the program name and add the -nostdlib parameter, the program runs successfully
> ![image](https://user-images.githubusercontent.com/45136205/122152474-ec01fe00-ce93-11eb-8f50-f55c270d4472.png)
> But when I wanted to make the program more complex, I found that I couldn't do it.It seemed like I should include a header file, but I didn't know how to do it, and I tried for a long time without success.Any help will be greatly appreciated
> ![image](https://user-images.githubusercontent.com/45136205/122154100-cf1afa00-ce96-11eb-96a7-d2a18fbd9c79.png)

突然看到作者是中国人，膜拜大神，我刚才在closed的问题里面看到有人也有这个问题，但是不知道他是怎么解决的。刚开始学习嵌入式，烦请大神指点。

**Comment by vowstar** [comment]
@Edward-Elric233 由于k210的内存实在是太小了，导致tcc编译器是被魔改后才能在k210上用起来，而且为了让rootfs足够小，我拼命的裁减了c库，导致很多引用的头文件都找不到。不过如果你想引用其他c函数的话，是有一个办法：
https://github.com/vowstar/k210-linux-nommu/blob/master/k210_lib
直接在这里面加，加完后重新按照文档的流程编译这个``k210_lib``就可以了
```bash
cd "$PROJ_ROOT/k210_lib"    
make    
make DESTDIR=$(pwd)/../rootfs_k210 install
```
比如``printf``的``stdio.h``也被我裁减了，我制作了一个假的放在了这里：
https://github.com/vowstar/k210-linux-nommu/blob/master/k210_lib/printf.c
你可以用类似的方式添加需要的函数和“头文件”。

**Comment by Edward-Elric233** [comment]
> @Edward-Elric233 由于k210的内存实在是太小了，导致tcc编译器是被魔改后才能在k210上用起来，而且为了让rootfs足够小，我拼命的裁减了c库，导致很多引用的头文件都找不到。不过如果你想引用其他c函数的话，是有一个办法：
> https://github.com/vowstar/k210-linux-nommu/blob/master/k210_lib
> 直接在这里面加，加完后重新按照文档的流程编译这个`k210_lib`就可以了
> 
> ```shell
> cd "$PROJ_ROOT/k210_lib"    
> make    
> make DESTDIR=$(pwd)/../rootfs_k210 install
> ```
> 
> 比如`printf`的`stdio.h`也被我裁减了，我制作了一个假的放在了这里：
> https://github.com/vowstar/k210-linux-nommu/blob/master/k210_lib/printf.c
> 你可以用类似的方式添加需要的函数和“头文件”。

好的，我尝试一下，非常感谢您的帮助
