### ISSUE TITLE
KD233 Support?

### ISSUE THREAD

**Issue by jdspdx** [vowstar/k210-linux-nommu#15]
Hello!

Thanks for the great writeup and tooling! I was able to get everything built, and flashed to kd233 using `-B kd233` instead of `-B dan`. 

However, when the KD233 boots I only get garbage on the UART. Sometimes, I get the first line of Linux booting but never more than this:
`    0.000000] Linux version 5.6.0-rc1vowstar (j@d) (gcc version`

Is there any configuration difference for the KD233 that must be done? Thanks!

**Comment by vowstar** [comment]
KD233 has many hardware problems, and its UART circuit uses the wrong voltage. It is not recommended to use this board.

**Comment by jdspdx** [comment]
@vowstar thank you for the information
