### ISSUE TITLE
Cannot use the tcc binary

### ISSUE THREAD

**Issue by pcotret** [vowstar/k210-linux-nommu#2]
I followed the tutorial. Everything works fine until the test of the `tcc` compiler with an "Hello world" C file.
```bash
tcc -run -nostdlib main.c
```
It doesn't work (my terminal cannot find `tcc`). It seems normal to me as `tcc` is not in `PATH`. Then, I've tried : 
```bash
../rootfs_k210/usr/bin/tcc -run -nostdlib main.c 
bash: ../rootfs_k210/usr/bin/tcc: cannot execute binary file: Exec format error
```
Still an error (not sure what this one means... :confused: )

**Comment by vowstar** [comment]
> I followed the tutorial. Everything works fine until the test of the `tcc` compiler with an "Hello world" C file.
> 
> ```shell
> tcc -run -nostdlib main.c
> ```
> 
> It doesn't work (my terminal cannot find `tcc`). It seems normal to me as `tcc` is not in `PATH`. Then, I've tried :
> 
> ```shell
> ../rootfs_k210/usr/bin/tcc -run -nostdlib main.c 
> bash: ../rootfs_k210/usr/bin/tcc: cannot execute binary file: Exec format error
> ```
> 
> Still an error (not sure what this one means... 😕 )

Check the file format in your ``$PROJ_ROOT/rootfs_k210/usr/bin/tcc`` on your host machine:

```bash
file $PROJ_ROOT/rootfs_k210/usr/bin/tcc
```

and what format is?

The NOMMU linux of k210 can't support ELF format, only support bFLT format. You may missing some environment variables when compile tcc.

Please delete your rootfs_k210, clean this project, run these scripts in order and don't touch other things:

```
cd $PROJ_ROOT
./prepare_buildroot.sh
./prepare_k210_cpio.sh
./prepare_k210_bin.sh
```
 Try again.

**Comment by pcotret** [comment]
- `tcc` format: `ff`. Seems normal, I forgot it was a bFLT-only version.
- If I follow the last 4 lines, everything works, my bad...

I can confirm it works on the Maixduino :+1: 

[![demo](https://asciinema.org/a/S0jFEuCQKg6YqRAycDLOxcq66.svg)](https://asciinema.org/a/S0jFEuCQKg6YqRAycDLOxcq66?autoplay=1)
