### ISSUE TITLE
make error after type "make"

### ISSUE THREAD

**Issue by Kingxukai** [vowstar/k210-linux-nommu#20]
make[2]: *** No rule to make target 'headers_install'.  Stop.
make[1]: *** [package/pkg-generic.mk:250: ~/test/k210-linux-nommu/riscv64-nommu-buildroot/output/build/linux-headers-custom/.stamp_configured] Error 2
make: *** [Makefile:84: _all] Error 2

**Comment by illantalex** [comment]
Excuse me, I've also encountered this issue trying to compile the toolchain on Ubuntu 24.10, how were you able to fix it?
