### ISSUE TITLE
How to add stdio.h

### ISSUE THREAD

**Issue by jiangotto** [vowstar/k210-linux-nommu#8]

**Comment by vowstar** [comment]
the tcc already have stdio library, just use #include <stdio.h>
if you want more function, please add it to https://github.com/vowstar/k210-linux-nommu/blob/master/k210_lib/stdio.h, and https://github.com/vowstar/k210-linux-nommu/tree/master/k210_lib
this is the stdio which uses in this firmware.

**Comment by jiangotto** [comment]
![image](https://user-images.githubusercontent.com/57144136/96678292-01c23080-13a4-11eb-8b27-04a64a937873.png)
那么请问这个问题应该怎么解决

**Comment by jiangotto** [comment]
我用find -name stdio.h找不到stdio.h

**Comment by jiangotto** [comment]
solved

**Comment by vowstar** [comment]
太好了
