### ISSUE TITLE
about glibc

### ISSUE THREAD

**Issue by jiangotto** [vowstar/k210-linux-nommu#9]
请问有意向将c标准库移植进去吗

**Comment by vowstar** [comment]
> 请问有意向将c标准库移植进去吗

glibc这个实在是太大了，当初因为种种原因SRAM砍到了8MiB, 相当不够用。我在想除非加个SD卡之类的东西，全部使用虚拟内存并且开启tmpfs才有这个可能。

**Comment by jiangotto** [comment]
> > 请问有意向将c标准库移植进去吗
> 
> glibc这个实在是太大了，当初因为种种原因SRAM砍到了8MiB, 相当不够用。我在想除非加个SD卡之类的东西，全部使用虚拟内存并且开启tmpfs才有这个可能。

那么像dietlibc等轻量级的有可能移植吗

**Comment by vowstar** [comment]
我们之前进行过newlib的移植，理论上dietlibc原理应该差不多，但是得花时间折腾

**Comment by jiangotto** [comment]
> 我们之前进行过newlib的移植，理论上dietlibc原理应该差不多，但是得花时间折腾

那么移植了newlib的版本愿意到github吗

**Comment by vowstar** [comment]
https://github.com/kendryte/kendryte-newlib
就在这里，尽管我已经离开这个公司了

**Comment by jiangotto** [comment]
> https://github.com/kendryte/kendryte-newlib
> 就在这里，尽管我已经离开这个公司了

感谢感谢
